# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-12 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer3D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('thumb_img', models.ImageField(blank=True, upload_to='')),
                ('detail_img', models.ImageField(blank=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
