# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-26 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer3d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer3d',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
